defaults:
  - _self_
  - stem: pointcloud_canteen_vit_mtokens
  - head: diff_transformer
  - dataset: sim_traj_dataset
  - dataloader: dataloader
  - val_dataloader: val_dataloader
  - network: policy
  - optimizer: adamw
  - lr_scheduler: cosine
  - warmup_lr: warmup_lr
  - rollout_runner: rollout_runner

# Training mode configuration
train_mode: auto  # "auto", "single", or "distributed"
world_size: 4     # Number of GPUs for distributed training

# Hydra configuration
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
  help:
    template: 'Unified PPT Learning Training

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    app_name: ${hydra.job.name}
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: RUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=RUN
    task: []
  job:
    name: run_train
    chdir: null
    override_dirname: ''
    id: ???
    num: ???
    config_name: config_unified
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.2.0
    version_base: '1.2'
    cwd: /Users/Eric/Downloads/ppt_learning
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /Users/Eric/Downloads/ppt_learning/configs
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      stem: pointcloud_canteen_vit_mtokens
      head: diff_transformer
      dataset: sim_traj_dataset
      dataloader: dataloader
      val_dataloader: val_dataloader
      network: policy
      optimizer: adamw
      lr_scheduler: cosine
      warmup_lr: warmup_lr
      rollout_runner: rollout_runner
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false

# Domain and dataset configuration
domains: place_crayon_phase2
dataset_path: data/place_crayon_dataset
output_dir: outputs/models
debug: false
seed: 42
suffix: ""
wb_tag: default

# Training configuration
train:
  total_epochs: 100
  total_iters: 100000
  epoch_iters: 1000
  freeze_trunk: false
  pretrained_dir: ""
  last_k_checkpoints: 5  # Number of checkpoints to keep

# Logging and saving
log_interval: 10
save_interval: 10

# Evaluation configuration  
parallel_eval: false