seed: 42
output_dir: ${hydra:runtime.output_dir}
wb_tag: ${suffix}
log_interval: 10
script_name: ''
pretrained_dir: ''
parallel_eval: false
env_names: [
    "Isaac-UR5-PutBowlInMicroWaveAndClose-Joint-Mimic-Retry-v0"
  ]
debug: False # Turn off to allow wandb logging
suffix: "debug" # suffix for the experiment

batch_size: 128

defaults:
  - env: isaacsim # rlbench # gensim2
  - network: depth
  - datasetsize: all
  - _self_

dataset:
  ignored_keys: ["language", "initial_state", "states", "images", "color", "abs_gripper_pos", "pointcloud", "wbc_target", "wbc_step", "last_action"]
  norm_depth: False
  augment_depth: True

dataloader:
  batch_size: ${batch_size}
  num_workers: 15
  pin_memory: true
  persistent_workers: true
  shuffle: true
  drop_last: true
  prefetch_factor: 2
val_dataloader:
  batch_size: ${batch_size}
  num_workers: 4
  shuffle: false
  pin_memory: false
  persistent_workers: false
  drop_last: true
optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0001
  eps: 1.0e-08
  weight_decay: 1.0e-06
  betas:
  - 0.95
  - 0.999
warmup_lr:
  lr: 1.0e-03
  step: 500
lr_scheduler: "cosine"
# lr_scheduler:
#   _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
#   T_0: 6
#   T_mult: 15
#   eta_min: 1.0e-08
train:
  total_epochs: 250  # maximum training epochs before termination. usually set as maximum
  total_iters: 100000000 # maximum training steps before termination
  epoch_iters: 1000  # training steps in each epoch
  validation_iters: 100 # maximum iterations for validation
  pretrained_dir: "" # pretrained model path for testing
  freeze_trunk: False # whether to freeze the trunk during finetuning