seed: 42
output_dir: outputs/pcd/${now:%Y-%m-%d_%H-%M-%S}
log_interval: 10
script_name: ''
parallel_eval: false
env_names: [
    "Isaac-UR5-PutBowlInMicroWaveAndClose-Joint-Mimic-Retry-v0"
  ]
debug: False # Turn off to allow wandb logging
suffix: "" # suffix for the experiment
wb_tag: ${suffix}

batch_size: 256 # batch size

defaults:
  - env: isaacsim # rlbench # gensim2
  - network: pcd
  - datasetsize: all
  - _self_

dataset:
  ignored_keys: ["language", "initial_state", "states", "depths", "images", "color", "abs_gripper_pos", "wbc_target", "wbc_step", "last_action"]
  # use_lru_cache: false
  
dataloader:
  batch_size: ${batch_size}
  num_workers: 4
  pin_memory: true
  persistent_workers: true
  shuffle: true
  drop_last: true
  prefetch_factor: 2
val_dataloader:
  batch_size: ${batch_size}
  num_workers: 4
  shuffle: false
  pin_memory: true
optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0001
  eps: 1.0e-08
  weight_decay: 1.0e-06
  betas:
  - 0.95
  - 0.999
warmup_lr:
  lr: 1.0e-03
  step: 500
lr_scheduler: "cosine"
# lr_scheduler:
#   _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
#   T_0: 250
#   T_mult: 1
#   eta_min: 1.0e-08
train:
  total_epochs: 500 # maximum training epochs before termination. usually set as maximum
  total_iters: 1000000000 # maximum training steps before termination
  epoch_iters: 500  # training steps in each epoch, not used
  validation_iters: 100 # maximum iterations for validation
  pretrained_dir: ""
  # pretrained_dir: "/mnt/bn/robot-minghuan-debug/ppt_learning/outputs/pcd/2025-05-30_01-10-05/ur5_put_bowl_in_microwave_and_close/530_add_gohome_data/model_500.pth" # pretrained model path for testing
  freeze_trunk: False # whether to freeze the trunk during finetuning