seed: 42
output_dir: outputs/depth/${now:%Y-%m-%d_%H-%M-%S}
log_interval: 10
script_name: ''
pretrained_dir: ''
parallel_eval: false
env_names: [
  "Isaac-UR5-PutBowlInMicroWaveAndClose-Joint-Mimic-Retry-v0"
]
debug: False # Turn off to allow wandb logging
suffix: "" # suffix for the experiment
wb_tag: ${suffix}

batch_size: 512 # batch size

defaults:
  - env: isaacsim # rlbench # gensim2
  - network: depth
  - datasetsize: all
  - _self_

domains: example  # assume there are example.zarr under dataset_path
save_interval: 10
dataset_path: <path to your dataset folder>

dataset:
  ignored_keys: ["language", "initial_state", "states", "images", "color", "abs_gripper_pos", "pointcloud", "wbc_target", "wbc_step", "last_action"]
  norm_depth: false
  augment_depth: true
  use_lru_cache: true
  action_horizon: 16 # observation: (observation + action) is action horizon 
  observation_horizon: 1 # before observation horizon is observation

dataloader:
  batch_size: ${batch_size}
  num_workers: 15
  pin_memory: true
  persistent_workers: true
  shuffle: true
  drop_last: true
val_dataloader:
  batch_size: ${batch_size}
  num_workers: 2
  shuffle: false
  pin_memory: false
  persistent_workers: false
  drop_last: true
optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0001
  eps: 1.0e-08
  weight_decay: 1.0e-06
  betas:
  - 0.95
  - 0.999
warmup_lr:
  lr: 1.0e-03
  step: 500
lr_scheduler: "cosine"
train:
  total_epochs: 1200 # maximum training epochs before termination. usually set as maximum
  total_iters: 1000000000 # maximum training steps before termination
  epoch_iters: 500  # training steps in each epoch
  validation_iters: 100 # maximum iterations for validation
  pretrained_dir: "" # pretrained model path
  freeze_trunk: False # whether to freeze the trunk during finetuning
  last_k_checkpoints: 5 # number of last checkpoints to keep
