seed: 42
output_dir: ${hydra:runtime.output_dir}
wb_tag: ${suffix}
log_interval: 10
script_name: ''
pretrained_dir: ${train.pretrained_dir}
parallel_eval: false
env_names: [
    "Isaac-UR5-PutBowlInMicroWaveAndClose-Joint-Mimic-v0"
  ]
debug: False # Turn off to allow wandb logging
suffix: "" # suffix for the experiment

defaults:
  - env: isaacsim # rlbench # gensim2
  - network: depth
  - datasetsize: all
  - _self_

network:
  openloop_steps: 12
  # temporal_agg: true

state_dim: 20
action_dim: 7

train:
  total_epochs: 250  # maximum training epochs before termination. usually set as maximum
  total_iters: 100000000 # maximum training steps before termination
  epoch_iters: 1000  # training steps in each epoch
  validation_iters: 100 # maximum iterations for validation
  pretrained_dir: "/mnt/xiaoshen/code/IsaacLab-new/GR-Isaaclab/outputs/ppt_learning/outputs/depth/2025-06-11_03-09-41/ur5_put_bowl_in_microwave_and_close/test_depth_ddp4" # pretrained model path for testing
  model_names:
    - model_50.pth 
    - model.pth
    # - model_450.pth
    # - model_400.pth
    # - model_350.pth
    # - model_300.pth
    # - model_250.pth
    - model_100.pth
  freeze_trunk: False # whether to freeze the trunk during finetuning
prompt: ""
rollout_runner:
  obs_mode: "depth"
  episode_num: 50
  hist_action_cond: true
  warmup_step: 30
  save_video: true
  # task_name: "Isaac-UR5-PutBowlInMicroWaveAndClose-Joint-Mimic-v0"
  task_name: "Isaac-UR5-PutBowlInMicroWaveAndClose-Joint-GoHome-Retry-Place-OneCamera-NoCrop-Mimic-v0"
eval_log_name: "eval_log_l40_8_100_ddp_new"
n_procs: 8
domains: ur5_put_bowl_in_microwave_and_close
stem:
  pointcloud: 
    pretrained_path: ""
