seed: 42
output_dir: ${hydra:runtime.output_dir}
wb_tag: ${suffix}
log_interval: 10
script_name: ''
pretrained_dir: ${train.pretrained_dir}
parallel_eval: false
env_names: [
    "Isaac-UR5-PutBowlInMicroWaveAndClose-Joint-Mimic-v0"
  ]
debug: False # Turn off to allow wandb logging
suffix: "" # suffix for the experiment

defaults:
  - env: isaacsim # rlbench # gensim2
  - network: pcd
  - datasetsize: all
  - _self_

network:
  openloop_steps: 12
  # temporal_agg: true

train:
  total_epochs: 550  # maximum training epochs before termination. usually set as maximum
  total_iters: 100000000 # maximum training steps before termination
  epoch_iters: 1000  # training steps in each epoch
  validation_iters: 100 # maximum iterations for validation
  pretrained_dir: "/home/ubuntu/xiaoshen/code/IsaacLab-new/GR-Isaaclab/outputs/ppt_learning/outputs/pcd/2025-05-26_15-48-19/ur5_put_bowl_in_microwave_and_close" # pretrained model path for testing
  model_names:
    - model.pth
    - model_450.pth
    - model_500.pth
    - model_400.pth
    - model_350.pth
    - model_300.pth
    - model_250.pth
    - model_200.pth
  freeze_trunk: False # whether to freeze the trunk during finetuning
prompt: ""
rollout_runner:
  hist_action_cond: true
  warmup_step: 30
  save_video: true
  task_name: "Isaac-UR5-PutBowlInMicroWaveAndClose-Joint-Mimic-v0"
  # task_name: "Isaac-UR5-CloseMicroWave-Mimic-v0"
eval_log_name: "eval_log_l40_8_100_ddp_new"
n_procs: 8
domains: ur5_put_bowl_in_microwave_and_close
stem:
  pointcloud: 
    pretrained_path: "/mnt/xiaoshen/scanobjectnn-pointnext-s_best.pth"
