seed: 42
output_dir: outputs/depth/${now:%Y-%m-%d_%H-%M-%S}
log_interval: 10
script_name: ''
pretrained_dir: ''
parallel_eval: false
env_names: [
    "Isaac-UR5-PutBowlInMicroWaveAndClose-Joint-Mimic-Retry-v0"
  ]
debug: False # Turn off to allow wandb logging
suffix: "" # suffix for the experiment
wb_tag: ${suffix}

batch_size: 512 # batch size

defaults:
  - env: isaacsim # rlbench # gensim2
  - network: depth
  - datasetsize: all
  - _self_

dataset:
  ignored_keys: ["language", "initial_state", "states", "images", "color", "abs_gripper_pos", "pointcloud", "wbc_target", "wbc_step", "last_action"]
  norm_depth: false
  augment_depth: true
  use_lru_cache: true
  hist_action_cond: true

dataloader:
  batch_size: ${batch_size}
  num_workers: 15
  pin_memory: true
  persistent_workers: true
  shuffle: true
  drop_last: true
val_dataloader:
  batch_size: ${batch_size}
  num_workers: 2
  shuffle: false
  pin_memory: false
  persistent_workers: false
  drop_last: true
optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0001
  eps: 1.0e-08
  weight_decay: 1.0e-06
  betas:
  - 0.95
  - 0.999
warmup_lr:
  lr: 1.0e-03
  step: 500
lr_scheduler: "cosine"
# lr_scheduler:
#   _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
#   T_0: 250
#   T_mult: 1
#   eta_min: 1.0e-08
train:
  total_epochs: 500 # maximum training epochs before termination. usually set as maximum
  total_iters: 1000000000 # maximum training steps before termination
  epoch_iters: 500  # training steps in each epoch
  validation_iters: 100 # maximum iterations for validation
  pretrained_dir: "/mnt/bn/robot-minghuan-debug/ppt_learning/outputs/depth/2025-06-19_21-02-17/ur5_put_bowl_in_microwave_and_close/one_camera_618_no_yaw_randomaffine_moreaug" # pretrained model path
  freeze_trunk: False # whether to freeze the trunk during finetuning