# @package _global_
domains: put_bowl_in_microwave_8_demos_generated_interrupt_520_collected_data_simplify_gripper_retry_more_wait_520 # dataset name to be loaded
save_interval: 50
dataset_path: /mnt/bn/robot-minghuan-datasets-lq/xiaoshen/datasets/ur5_put_bowl_in_microwave_and_close

# dataset config
dataset:
  # _target_: ppt_learning.dataset.multi_sim_traj_dataset.MultiTrajDataset
  _target_: ppt_learning.dataset.sim_traj_dataset.TrajDataset
  domain: "isaacsim"
  dataset_path: "" # TO be filled
  horizon: -1 # horizon for each dataset sample. should be action_horizon+observation_horizon-1 and will be replaced
  val_ratio: 0. # the train-validation ratio
  pad_after: ${dataset.action_horizon} # padding after the episode
  episode_cnt: 100 # total episodes
  step_cnt: 30000 # total data transitions
  data_augmentation: False # data augmentation
  se3_augmentation: False # se3 augmentation
  use_disk: True # use disk ins1tead of memory to store the data
  pad_before: ${dataset.observation_horizon} # padding before the episode
  data_ratio: 1 # only use a fraction of data
  action_horizon: 16 # observation: (observation + action) is action horizon 
  observation_horizon: 3 # before observation horizon is observation
  precompute_feat: True # precompute features using pretrained models for stems
  image_encoder: 'resnet' # which encoder to use as the pretrained model  
  dataset_encoder_postfix: "" # "_${dataset.image_encoder}" # another postfix
  use_multiview: False # use multiple camera views
  normalize_state: ${stem.normalize_state} # whether to normalize the states in datasets
  from_empty: False
  use_pcd: False # To be replaced
  pcdnet_pretrain_domain : "" # To be replaced
  pcd_channels: 4 # 3 is pos, 4 is [pos, height], 5 is [pos, height, seg], 6 is [pos, color], 7 is [pos, color, height]
  action_key: "wbc_target/r" # actions
  pose_transform: "quat_to_pose"

# test
rollout_runner:
  _target_: ppt_learning.utils.rollout_runner.IsaacEnvRolloutRunner
  headless: true
  episode_num: 100
  # save_video: True
  max_timestep: 2000
  obs_mode: "pointcloud"
  pcdnet_pretrain_domain : "" # To be replaced
  pcd_channels: ${dataset.pcd_channels}
  video_save_dir: "${train.pretrained_dir}/eval_video"